### ISSUE TITLE
Questions about dataset usage

### ISSUE THREAD

**Issue by chophilip21** [ykdai/Flare7K#10]
Hi, first of all, thanks a lot for coming up with such a great dataset!

For flare removal, definitely the most difficult aspect is generating the dataset for sure. I would love to use your data for training the model that I am developing, but I am planning on deploying the models to the IOS app that I am developing in the future. I realize your dataset is under `S-Lab License 1.0`, so I am aware of having to contact you to ask for your permission. Do you strictly prohit commercial use? It would be really great to be able to use your data.

**Comment by ykdai** [comment]
Thank you so much for your interest! For commercial use, please consult my professor Prof. Cavan. He will tell you the details of how to apply for the permission for this dataset. His e-mail is [ccloy@ntu.edu.sg](ccloy@ntu.edu.sg).

**Comment by chophilip21** [comment]
Got it. Thank you so much!
