### ISSUE TITLE
Is there an error in your data_loader.py?

### ISSUE THREAD

**Issue by Shanxing1** [ykdai/Flare7K#11]
In your data_loader.py, class Flare_Image_Loader, there are some codes to transform the PIL image to tensor:
`		if self.transform_base is not None:
                        base_img=to_tensor(base_img)
                        base_img=adjust_gamma(base_img)
                        base_img=self.transform_base(base_img)
		else:
			base_img=to_tensor(base_img)
			base_img=adjust_gamma(base_img)
			base_img=base_img.permute(2,0,1)
`

in the ELSE branch, is 'base_img=base_img.permute(2,0,1)' still needed? I think the to_sensor function already did this, when I didn't use transform_base, there was an error about dimension.

**Comment by ykdai** [comment]
Thank you so much for your correction. I think you are right, I have removed this line in the dataloader. 
Thank you again for your kind feedback : )
