### ISSUE TITLE
score

### ISSUE THREAD

**Issue by wusiqi521** [ykdai/Flare7K#12]
Sorry to bother you again, I saw some of the data you provided, thank you very much, but I couldn't find gt and mask for the test image，i want to compare with other players

**Comment by Nukaliad** [comment]
Have you checked the path:
├── test_data
     ├── real
          ├── input
          ├── gt
          ├── mask
     ├── synthetic
          ├── input
          ├── gt
	  ├── mask

**Comment by wusiqi521** [comment]
Sorry, I was referring to the test image from the 2023 challenge

**Comment by ykdai** [comment]
We have discussed with the MIPI organizers whether to release the gt and masks. They thought the gt may be still used in future competitions, thus, we do not have plans to release it. You can use the Flare7K's test set for evaluation. Sorry for the inconvenience.
