### ISSUE TITLE
Could you share the code for aperture generation?

### ISSUE THREAD

**Issue by coolbunnyx** [ykdai/Flare7K#13]
Nice work! Could you release the code for aperture generation, especially the streak one that shown in Supplementary Material Figure 2(b)? Thanks!

**Comment by ykdai** [comment]
Thanks for your interests. These lines in the aperture is simulated by using fractal noise in Adobe After Effect. You can refer to this: https://www.youtube.com/watch?v=ZrN7nGkJys0

If you want to use python to generate it, you can also try to use perlin noise and resize it.  You will get the same results.

**Comment by coolbunnyx** [comment]
> Thanks for your interests. These lines in the aperture is simulated by using fractal noise in Adobe After Effect. You can refer to this: https://www.youtube.com/watch?v=ZrN7nGkJys0
> 
> If you want to use python to generate it, you can also try to use perlin noise and resize it. You will get the same results.

It worked. Thanks!
