### ISSUE TITLE
Is the real world result of the paper (Uformer PSNR = 26.98) tested on the 100 images provided by the project? Which model can be used to get such a result?

### ISSUE THREAD

**Issue by qulishen** [ykdai/Flare7K#15]

**Comment by qulishen** [comment]
I saw your logs. Maybe you tested on the previous 20 real data sets. If so,can you provide the previous 20 data sets? Thank u.

**Comment by qulishen** [comment]
We test the pretrained models of uformer in real world dataset by using the `python evaluate.py --input result/test_real/flare7k/blend/ --gt dataset/Flare7Kpp/test_data/real/gt/`, and the PSNR are 26.416 and 26.799499dB with/without reflection model

**Comment by ykdai** [comment]
The reported results are based on our current dataset with 100 images. Are you using the `python test.py --input dataset/Flare7Kpp/test_data/real/input --output result/test_real/flare7k/ --model_path experiments/flare7k/net_g_last.pth` for inference? If so, I think the result should be 26.98.

**Comment by qulishen** [comment]
Thank you, I confused test.py with test_large.py. Could you please explain why the two results are different? I set them both to a light source recovery threshold of 0.97.

**Comment by ykdai** [comment]
I think the problem is from the calculation error in the overlapped region's interpolation. We may fix this problem soon.
