### ISSUE TITLE
Validation set problem

### ISSUE THREAD

**Issue by JZhu1208** [ykdai/Flare7K#16]
Could you please provide more details about the validation set during the training process? About how to generate a validation set, or how to select a validation set? Thank you so much

**Comment by ykdai** [comment]
Thank you for the interest. [generate_flare.ipynb](https://github.com/ykdai/Flare7K/blob/main/generate_flare.ipynb) can help generate paired flare-corrupted and flare-free images as validation set.

**Comment by JZhu1208** [comment]
Okay, got it. Thank you for your kind reply.
