### ISSUE TITLE
关于test imgaes

### ISSUE THREAD

**Issue by steven30currry** [ykdai/Flare7K#2]
作者你们好
请问可以提供100张测试图片吗，貌似不在github上

**Comment by ykdai** [comment]
Thank you for your interest. Have you downloaded the flares dataset? There is a test_data folder with 100 synthetic and 100 real images in our Flare7K dataset.

**Comment by steven30currry** [comment]
是我疏忽了，谢谢啦！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ykdai/Flare7K"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月25日(星期五) 中午12:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ykdai/Flare7K] 关于test imgaes (Issue #2)





 
Thank you for your interest. Have you downloaded the flares dataset? There is a test_data folder with 100 synthetic and 100 real images in our Flare7K dataset.
