### ISSUE TITLE
Validation dataset problem

### ISSUE THREAD

**Issue by JZhu1208** [ykdai/Flare7K#21]
Hello, I would like to ask the following questions about the validation dataset:

1. Are the flare-free images generated for the validation dataset consistent with the 'gt' images in 'test_data/real/' or '\test_data\synthetic'? If it's not consistent, was it selected in 'Flickr24K'? Could you kindly provide it?

2. Is the flare pattern used when generating the validation dataset the pattern provided in flare7K++?

Looking forward to your reply. Thank you.

**Comment by ykdai** [comment]
1. For the validation dataset, we collect a real-captured flare-free image dataset as background images. Then, we use [generate_flare.ipynb](https://github.com/ykdai/Flare7K/blob/main/generate_flare.ipynb) script to create a private dataset for validation.
2.  We still used flares from the flare7k++ to synthesize the validation data.
