### ISSUE TITLE
Can you please provide lens flare segmentation network training code with its checkpoint

### ISSUE THREAD

**Issue by GopiRajuMatta** [ykdai/Flare7K#22]
Hello!

In Flare7k++ paper, you mentioned lens flare segmentation as one of the potential applications. Can you please provide the network(PSPNet) training code with its checkpoint, I am planning to use it for one of my works. 

Otherwise, can you please provide gt segmentation masks, so that I can train the network by myself.

Thank you
Gopi

**Comment by ykdai** [comment]
We are using [mmseg](https://github.com/open-mmlab/mmsegmentation) for training. However, we do not have plans to provide  its checkpoint. For gt segmentation masks, you can set a threshold for the glare and streak annotations for training.

**Comment by GopiRajuMatta** [comment]
Sure, will try it out, thank you for the response..
