### ISSUE TITLE
Training with U-Net

### ISSUE THREAD

**Issue by clue3clue32** [ykdai/Flare7K#24]
Hi, I was trying to reproduce the training process of Unet with <code>unet_arch.py</code> under the <code>basicsr/archs</code> folder.
I changed the parameter 'type' of 'network_g' to 'U_Net' and remove the 'img_size' in <code>uformer_flare7kpp_baseline_option.yml</code>. No errors were reported during the training process. 
The results of running <code>test.py</code> on checkpoints  are as follows :
net_g_5000:
![00000_blend_5000](https://github.com/ykdai/Flare7K/assets/105770086/2a6b3353-45e9-44e1-a73e-86017d635a47)
net_g_10000:
![00000_blend_10000](https://github.com/ykdai/Flare7K/assets/105770086/26790564-056d-49fe-bd76-fbe71b765097)
net_g_25000:
![00000_blend_25000](https://github.com/ykdai/Flare7K/assets/105770086/a5231163-04dd-4f28-a875-f553698ede6f)
What led to the occurrence of this problem? Thank you!

**Comment by ykdai** [comment]
Have you ever tried to modify the config using U-Net based on 'uformer_flare7k_option.yml'? In my memory, using U-Net on flare7kpp's setting is a little bit difficult to converge.

**Comment by clue3clue32** [comment]
Thanks for your reply, the results based on `uformer_flare7k_option.yml` under the `blend` folder are like this:
![00025_blend](https://github.com/ykdai/Flare7K/assets/105770086/0634831b-d67f-47cb-9a3e-7151997b6eb5)
![00006_blend](https://github.com/ykdai/Flare7K/assets/105770086/72e0a72e-75ce-441c-b3a2-7a12090252ae)

**Comment by ykdai** [comment]
Have you ever checked the dataloader's output of your training data, or can you report the trainning log? The seems that the deflared image is just the black image.

**Comment by RuoyuYoung** [comment]
请问有成功吗，使用unet进行训练，谢谢
