### ISSUE TITLE
paper和code参数不一致问题

### ISSUE THREAD

**Issue by qulishen** [ykdai/Flare7K#27]
您好！
对于Flare7K++论文中的实验细节提到 “ For the image in our flare dataset, a random rotation U(0, 2π), a random translation U(−300, 300), a random shear U(−π/9, π/9), a random scale U(0.8, 1.5)” ，该描述和代码中uformer_flare7kpp_baseline_option.yml 文件的设置不一致，应该以哪一个为准？
```python
    transform_base:
      img_size: 512
    transform_flare:
      scale_min: 0.7
      scale_max: 1.2
      translate: 100
      shear: 20
    mask_type: ~
```

**Comment by ykdai** [comment]
谢谢你的反馈，请以论文为主。后面release的option是我们整理代码时从之前的实验setting中copy后改过去的，因为我的疏忽，和我们最后release的ckpt的config没对齐。更改完后的版本已经update了。
