### ISSUE TITLE
How can i find the flickr24k dataset?

### ISSUE THREAD

**Issue by chenfeiyang0-0** [ykdai/Flare7K#30]
How can i find the flickr24k dataset?

**Comment by ykdai** [comment]
You can find it here: 'https://drive.google.com/file/d/1GNFGWfUbgXfELx5fZtjTjU2qqWnEa-Lr/view'

**Comment by chenfeiyang0-0** [comment]
OK，get it ,Thank you very much!



















At 2024-12-09 16:12:40, "Yuekun Dai" ***@***.***> wrote:

You can find it here: 'https://drive.google.com/file/d/1GNFGWfUbgXfELx5fZtjTjU2qqWnEa-Lr/view'
