### ISSUE TITLE
ModelNotFoundError

### ISSUE THREAD

**Issue by daeing** [ykdai/Flare7K#5]
Excuse me, I run the train script, It shows ModuleNotFoundError: No module named 'basicsr.archs.vgg_arch'? Is there missing some file?

**Comment by ykdai** [comment]
Thank you for reminding. I have updated it at `Flare7K/basicsr/archs/` , Could you run the train script now?

**Comment by daeing** [comment]
> Thank you for reminding. I have updated it at `Flare7K/basicsr/archs/` , Could you run the train script now?

It works norm now. Would mind update your environment.yaml file? Many thanks.

**Comment by ykdai** [comment]
Sure! We will update it soon.

**Comment by daeing** [comment]
> Sure! We will update it soon.

It's so kind of you if you update the inference code using your pretrained model.

**Comment by ykdai** [comment]
You can run the deflare.ipynb or change it to test.py for inference.

**Comment by daeing** [comment]
> You can run the deflare.ipynb or change it to test.py for inference.

OKOK
