### ISSUE TITLE
Evaluation dataset for the MIPI 2023 Night Speckle Removal Challenge

### ISSUE THREAD

**Issue by wusiqi521** [ykdai/Flare7K#7]
Can you publish the 100 data sets used to evaluate players in the challenge and the code used to calculate S-PSNR and G-PSNR?

**Comment by ykdai** [comment]
The MIPI test dataset will be released in this week. Please stay tuned : )

**Comment by wusiqi521** [comment]
Thank you very much, will the evaluation S/G-PSNR code also be provided on this site?

**Comment by ykdai** [comment]
Yes, it will be provided.

**Comment by wusiqi521** [comment]
Thank you again

**Comment by wusiqi521** [comment]
Sorry to bother you again, I saw some of the data you provided, thank you very much, but I couldn't find gt and mask for the test image

**Comment by ykdai** [comment]
To make evaluation fair, the gt and mask for MIPI 2023 test dataset are private. You can use the Flare7K's test set for evaluation. We are still discussing with the MIPI organizers whether to release the gt and masks or set up a kaggle/codalab page to help the users to evaluate their results. Please stay tuned.

**Comment by wusiqi521** [comment]
I'm sorry, I thought the end of the game could be announced, but I was reckless, thank you

**Comment by wusiqi521** [comment]
Sorry to bother you again, I have a question about the parameters in the code you provided. Why do you use "L_Abs_pure" for the loss name instead of "L_Abs"?

**Comment by ykdai** [comment]
You can check the code at basicsr/losses/flare_loss.py. In the paper of Wu et al., they set mask on the light source region and calculate the L_Abs outside the mask. So we still use L_Abs to represent that masked Abs loss. Thus, we call the original abs loss as L_Abs_pure.

**Comment by wusiqi521** [comment]
If we follow the loss presented by Wu et al., L_Abs is more suitable."
class L_Abs(nn.Module):
    def __init__(self):
        super(L_Abs, self).__init__()

    def forward(self,x,flare_gt,base_gt,mask_gt,merge_gt):
        base_predicted=base_gt*mask_gt+(1-mask_gt)*x
        flare_predicted=merge_gt-(1-mask_gt)*x
        base_loss=torch.abs(base_predicted-base_gt)
        flare_loss=torch.abs(flare_predicted-flare_gt)
        Abs_loss=torch.mean(base_loss+flare_loss)
        return Abs_loss

@LOSS_REGISTRY.register()
class L_Abs_pure(nn.Module):
    def __init__(self,loss_weight=1.0):
        super(L_Abs_pure, self).__init__()
        self.loss_weight=loss_weight

    def forward(self,x,flare_gt):
        flare_loss=torch.abs(x-flare_gt)
        Abs_loss=torch.mean(flare_loss)
        return self.loss_weight*Abs_loss

**Comment by wusiqi521** [comment]
Maybe I'm not sure about the output of your code, whether the loss content of wu is implemented when using L_Abs_pure in your uformer network？thanks.

**Comment by ykdai** [comment]
We directly output a 6-channel output with 3ch as flare-free image and another 3channel as flare image. When I reimplement Wu et al.'s code, I notice that L_Abs_pure works better than his masked loss.
Besides, we are going to release our Flare7K++ dataset and training code soon. It will be a little different. You can check the paper first: https://arxiv.org/abs/2306.04236. It contains more details.

**Comment by wusiqi521** [comment]
Thanks.



---Original---
From: "Yuekun ***@***.***&gt;
Date: Thu, Jun 8, 2023 23:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ykdai/Flare7K] Evaluation dataset for the MIPI 2023 NightSpeckle Removal Challenge (Issue #7)




 
We directly output a 6-channel output with 3ch as flare-free image and another 3channel as flare image. When I reimplement Wu et al.'s code, I notice that L_Abs_pure works better than his masked loss.
 Besides, we are going to release our Flare7K++ dataset and training code soon. It will be a little different. You can check the paper first: https://arxiv.org/abs/2306.04236. It contains more details.

**Comment by wusiqi521** [comment]
Hi! Running Flare7K's train.py has the following problems，I double-checked the path and datas , it looks good，：
Traceback (most recent call last):
  File "basicsr/train.py", line 219, in <module>
    train_pipeline(root_path)
  File "basicsr/train.py", line 161, in train_pipeline
    train_data = prefetcher.next()
  File "/home/lixueyuan/desk/wusiqi/Flare7K/basicsr/data/prefetch_dataloader.py", line 76, in next
    return next(self.loader)
  File "/home/lixueyuan/anaconda3/envs/puret/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/lixueyuan/anaconda3/envs/puret/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/lixueyuan/anaconda3/envs/puret/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/lixueyuan/anaconda3/envs/puret/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lixueyuan/anaconda3/envs/puret/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lixueyuan/anaconda3/envs/puret/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lixueyuan/anaconda3/envs/puret/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lixueyuan/desk/wusiqi/Flare7K/basicsr/data/flare7k_dataset.py", line 95, in __getitem__
    base_img=adjust_gamma(base_img)
  File "/home/lixueyuan/desk/wusiqi/Flare7K/basicsr/data/flare7k_dataset.py", line 32, in __call__
    return TF.adjust_gamma(image,self.gamma,gain=1)
  File "/home/lixueyuan/anaconda3/envs/puret/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 721, in adjust_gamma
    raise TypeError('img should be PIL Image. Got {}'.format(type(img)))
TypeError: img should be PIL Image. Got <class 'torch.Tensor'>

if i could get your help ,i would be extremely grateful!!!

**Comment by Nukaliad** [comment]
You should update your torch version. If you use the pytorch with version before v1.6, this error may occur.

**Comment by wusiqi521** [comment]
！！！！！Thank you very much！！！！



---Original---
From: ***@***.***&gt;
Date: Fri, Jun 9, 2023 16:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ykdai/Flare7K] Evaluation dataset for the MIPI 2023 NightSpeckle Removal Challenge (Issue #7)




 
You should update your torch version. If you use the pytorch with version before v1.6, this error may occur.

**Comment by wusiqi521** [comment]
hello,I see you posted the latest parameter file, please ask if FlareKPP has a more robust problem only training scattering glare.

**Comment by ykdai** [comment]
Since Flare-R subset also contains reflective flare, training with Flare7K++ cannot avoid removing tiny bright spots around the light source. Thus, only training with scattering flares can’t solve this problem. However, our new training pipeline and realistic dataset can already achieve good results. In my experiment, I notice that only training scattering flares often lead to similar results with our ckpt. Thus, we just release one checkpoint for Flare7Kpp.

**Comment by wusiqi521** [comment]
thank you！



---Original---
From: "Yuekun ***@***.***&gt;
Date: Sat, Jun 17, 2023 10:25 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ykdai/Flare7K] Evaluation dataset for the MIPI 2023 NightSpeckle Removal Challenge (Issue #7)




 
Since Flare-R subset also contains reflective flare, training with Flare7K++ cannot avoid removing tiny bright spots around the light source. Thus, only training with scattering flares can’t solve this problem. However, our new training pipeline and realistic dataset can already achieve good results. In my experiment, I notice that only training scattering flares often lead to similar results with our ckpt. Thus, we just release one checkpoint for Flare7Kpp.
